### ISSUE TITLE
Add rosenpass version command

### ISSUE THREAD

**Issue by marek22k** [rosenpass/rosenpass#105]
Hello,

I would find a version command quite helpful. For example, when writing bug reports, you know exactly with which version it occurred. If necessary, you could include not only the version number, but also the git commit.
```
$ rosenpass version
error: unrecognized subcommand 'version'

Usage: rosenpass <COMMAND>

For more information, try '--help'.
```

**Comment by emilengler** [comment]
You can already do `rosenpass -V` or `rosenpass --version`

**Comment by stv0g** [comment]
I agree here with @emilengler. Lets keep is short and simple.

**Comment by emilengler** [comment]
I will close this then.

**Comment by lamr02n** [comment]
We have decided to reject this issue due to the already available options `rosenpass -V` and `rosenpass --version`.
