### ISSUE TITLE
Some nits within the whitepaper

### ISSUE THREAD

**Issue by emilengler** [rosenpass/rosenpass#108]
@wucke13 and I just went through the whitepaper together and found some slight issues, which are as follows:

* `s/private/secret/g`
* `s/server/responder/g`
* Renaming `pidiC` to `pidict` to imply its ciphertext nature
* What do the results in the `Global Domain` diagram mean? Are they hash functions, are they hash inputs?
    * Consider expanding the legend; explain what `>` and `>>` mean a bit further

**Comment by stv0g** [comment]
Maybe we can track those in #68?
Or create independent issues for alle WP related things?

**Comment by AliceOrunitia** [comment]
Hi, Karo just wanted me to say that she'll respond to this next week, as she's busy right now as she has a priority deadline regarding the Avionics paper.

**Comment by stv0g** [comment]
Lets close this in favour of https://github.com/rosenpass/rosenpass/issues/68#issuecomment-1718029441
