### ISSUE TITLE
FreeBSD: can't assign requested address

### ISSUE THREAD

**Issue by clausecker** [rosenpass/rosenpass#116]
When I try to run the `rp` script from rosenpass 0.2.0-rc.1 following the instructions given in rp(1), binding to the interface fails:

```
# rp exchange server.rosenpass-secret dev rosenpass0 listen 192.168.0.1:9999 peer client.rosenpass-public allowed-ips fe80::/64
rosenpass0
[2023-09-05T14:54:06Z ERROR rosenpass] Can't assign requested address (os error 49)
```

This is likely because the `rp` script does not actually assign any IP address to the newly created interface.  Without an address, the socket cannot be bound to it.  How is this supposed to work?

**Comment by clausecker** [comment]
Okay, this is an operator error.  You need to use the outbound IP address of your server here.  This could be clarified in the documentation.

**Comment by emilengler** [comment]
> Okay, this is an operator error. You need to use the outbound IP address of your server here. This could be clarified in the documentation.

Do you have the command that got it working for you?

**Comment by clausecker** [comment]
Yes, I had to use the actual address of my server or leave out that part.

Emil Engler ***@***.***> schrieb am Di., 5. Sep. 2023, 16:03:

**Comment by emilengler** [comment]
Instead of the 192.168.XXX.XXX?

**Comment by clausecker** [comment]
@emilengler Yes, correct.  This is the address on which `rosenpass` listens for incoming key exchange requests, so it must be an address the client can communicate with.  This is not explained in the `rp` tutorial.
