### ISSUE TITLE
Provide test coverage

### ISSUE THREAD

**Issue by emilengler** [rosenpass/rosenpass#125]
Rust provides many tools to generate a coverage report, most notably `grcov`.
I think it is a good way if we introduce scripts that wrap around and maybe even provide test coverage reports on our websites (grcov can output to HTML).

**Comment by stv0g** [comment]
I have good experiences with https://codecov.io/ as they can be nicely integrated in the CI as well as have usually much nicer ways of tracking coverage over time/commits as well as a nice rendering of code coverage than most of the open source tools.

**Comment by stv0g** [comment]
See: https://app.codecov.io/gh/cunicu/go-rosenpass/

**Comment by emilengler** [comment]
Thank you for letting me know!
It just happens that I already have experience with grcov :^)

I will have a look at the alternative you mentioned tomorrow, but after all every tool that can output lcov is more than sufficient.
