### ISSUE TITLE
no "rosenpass" in src?

### ISSUE THREAD

**Issue by grince** [rosenpass/rosenpass#131]
Hi everybody,

I just wanted to try Rosenpass on my laptop, but src/rosenpass is not available which should be used according to the documentation (and @ajuvo ;). Could you please check what happened there?

**Comment by emilengler** [comment]
Could you refer to the part in the documentation that refers to it?

**Comment by grince** [comment]
I read the readme.md.

first mentioned as part of the repository, then in the chapter about software architecture.

**Comment by emilengler** [comment]
Are you talking about the rosenpass binary? If you are using cargo to build it, you can find it within your target/ folder.

**Comment by grince** [comment]
well - from the readme I guessed the binary would "only" be a rust-file within the src-directory. But then sorry for the confusion, I'll see how to compile it under MacOS ;)

**Comment by ajuvo** [comment]
thanks for your input, we revise the whitepaper and instructions regularly.
