### ISSUE TITLE
Implement the cookie mechanism

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#137]
Implement the cookie mechanism as described in the [wireguard whitepaper](https://www.wireguard.com/papers/wireguard.pdf). Document this appropriately in the whitepaper.

**Comment by TouchstoneTheGreat** [comment]
@koraa Idk this desc. is enough or not. But I would like get more details on this !
> Implement the cookie mechanism as described in the [wireguard whitepaper](https://www.wireguard.com/papers/wireguard.pdf). Document this appropriately in the whitepaper.

**Comment by koraa** [comment]
> @koraa Idk this desc. is enough or not. But I would like get more details on this !
> 
> > Implement the cookie mechanism as described in the [wireguard whitepaper](https://www.wireguard.com/papers/wireguard.pdf). Document this appropriately in the whitepaper.

Sure! Could you please read sections 5.3, 5.4.4, 5.4.7, and 6.6 of the wireguard whitepaper? The cookie reply mechanism is described in detail there. The same mechanism should be implemented in Rosenpass and the mechanism should be described in our whitepaper too.

**Comment by TouchstoneTheGreat** [comment]
If you are maintainer I want ask is this good approach

1. Generate a random cookie for each handshake.
2. Send the cookie to the initiator in the first handshake message.
3.Compute a MAC of the cookie using the initiator's private key and send the MAC back to the responder in the second 4.handshake message.
5.Verify the MAC using the initiator's public key in the responder.

Can you suggest any other approaches ?

**Comment by koraa** [comment]
> If you are maintainer I want ask is this good approach
> 
>     1. Generate a random cookie for each handshake.
> 
>     2. Send the cookie to the initiator in the first handshake message.
>        3.Compute a MAC of the cookie using the initiator's private key and send the MAC back to the responder in the second 4.handshake message.
>        5.Verify the MAC using the initiator's public key in the responder.
> 
> 
> Can you suggest any other approaches ?

Did you take that from the whitepaper? I think there are some gaps in the plan if this sketch was supposed to be comprehensive. I would start by coming up with a rule deciding under which conditions the cookie mechanism will activate. It should not be active by default, only under contention.

**Comment by prabhpreet** [comment]
/attempt #137

@koraa Thanks for the pointers to the whitepaper. I'd like to attempt this, starting with the next draft PR edits to the whitepaper to confirm that the port to the cookie mechanism is what you have in mind, and comments regarding the cookie mechanism activation. Please review to let me know if I'm on the right track.

**Comment by melsonic** [comment]
Is this still open? @koraa

**Comment by koraa** [comment]
> Is this still open? @koraa

@melsonic I welcome your contributions to the repository, but please do not force me to do extra work answering obvious questions. If you would like to contribute to this talk to @prabhpreet who has obviously done a lot of work on this in the past couple of weeks.

I am not going to condone races or competition on any issues; @prabhpreet has done some work and I would reject even a perfect PR if its an attempt to scoop anyone else's work.

People should be sure their effort is honored when they put work into improving Rosenpass!

**Comment by ologbonowiwi** [comment]
Should this be closed?
