### ISSUE TITLE
Enforce code style on doc comments

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#156]
Make sure we have tooling to enforce our rust code style on rust examples in the documentation & readmes in the CI and make sure we have tooling to automatically format the same code during development.

**Comment by Min2who** [comment]
can i pick this up?
/attempt #156

**Comment by Min2who** [comment]
@koraa we can install formatting tool like "rustfmt" right?

**Comment by koraa** [comment]
@alankritdabral Thank you for your submission. This project already uses a linter: We use prettier and cargo format in the CI with a nix based setup. As the issue said, this issue is mainly about enforcing rust code style, i.e.  formatting code examples; sorry about having not been very clear about this in the readme.

I added a section to the description explaining that this is about code style of examples specifically.

I don't expect you to deal with nix, figuring out a way to run the rust linter on examples either in readmes or doc comments with any sort of scripting would be enough from me to accept a PR, but duplicating basic linting functionality won't add much.

Happy to tip you 10 dollars for your effort though…

**Comment by Min2who** [comment]
can you assign me this i can give a try

**Comment by Min2who** [comment]
Hey @koraa should i attempt this?

**Comment by alankritdabral** [comment]
/claim #156
@koraa
