### ISSUE TITLE
Fuzzing in CI

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#163]
Enable running the fuzzing code @pcwizz created in the CI. This is a smoke test to make sure fuzzing remains functional, we don't want to burn CPU cycles by actually trying lengthy fuzzing procedures during every CI run.

**Comment by Min2who** [comment]
can you assign me this @koraa

**Comment by ezhil56x** [comment]
@koraa The required changes should be made only to the `.gitlab-ci.yml` right? Correct me if I'm wrong ✨

**Comment by koraa** [comment]
> @koraa The required changes should be made only to the `.gitlab-ci.yml` right? Correct me if I'm wrong ✨

I think updating the QC github job would be optimal.

**Comment by ezhil56x** [comment]
@koraa I hope I have implemented it. Can I open a pull request?

**Comment by koraa** [comment]
> @koraa I hope I have implemented it. Can I open a pull request?

Always :)

**Comment by ezhil56x** [comment]
> > @koraa I hope I have implemented it. Can I open a pull request?
> 
> Always :)

Created pull request. If there are any changes to be done. Happy to do!

**Comment by koraa** [comment]
@Min2who @ezhil56x @melsonic I am not going to encourage trying to race for PR submission.

@ezhil56x Your PR is broken; and having to review a broken PR is extra work for me and managing PRs like that causes extra work for me. You are a first time collaborator so I need to approve the CI runs, I realize that makes your work harder. But still, I am spending extra time here.

As I said: Do coordinate with the others. Help each other turn this PR into a good PR, and if you all did work to make sure this issue gets resolved in a high-quality way that saves me some time and fits in well with the existing infrastructure in this project, I am happy to do the work to pay you for the time you did spent on making this work.

There is a lot to do to improve the code quality in Rosenpass. There are tests that should be written, benchmarks that should be created, functions that should be documented, user interfaces whose UX needs to be improved.

Do create issues, document how high a payment you think is appropriate for the issues. Work together, help each other collaborate. There is enough work to go around and enough funds to pay it reasonably!

**Comment by ezhil56x** [comment]
@koraa Figured out the problem what is the -max_len to be used to each fuzz

**Comment by ezhil56x** [comment]
Am I missing out something? Correct me if I'm wrong

**Comment by koraa** [comment]
> Am I missing out something? Correct me if I'm wrong

I don't know; I haven't spent much time looking into the particular subject, your infos sound fine!

**Comment by ezhil56x** [comment]
@koraa 

When I run
`cargo fuzz run fuzz_handle_msg`
`cargo fuzz run fuzz_mceliece_encaps`

I'm getting
`Error: Fuzz target exited with exit status: 77`

Rest of the fuzz run smoothly as expected. I have made all the necessary changes. I think there is some issue with `handle_msg` and `mceliece_encaps`. Once they are fixed the `qc.yml` will pass all tests

**Comment by koraa** [comment]
@pcwizz Can you check it out?

**Comment by pcwizz** [comment]
Ah when the fuzz targets patch was revised it added unwrapping the results of the functions being fuzzed. Turns out if you provide invalid data like an empty array to these functions they return errors which I suspect is the desired behavior. I can make a PR removing the unwraps as the fuzzing is about what happens inside the fuzz target rather than what is returned.

**Comment by pcwizz** [comment]
Seems the other targets don't error with bogus input so I just changed the 2 targets that do: https://github.com/rosenpass/rosenpass/pull/174

**Comment by ezhil56x** [comment]
@koraa I hope it works now as expected. Can you review it once?

**Comment by koraa** [comment]
Solved via @ezhil56x in #165 via #186; payout goes to @ezhil56x
