### ISSUE TITLE
Implement secret memory in pure rust

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#179]
Currently we are using libsodium's secret memory features through `sodium_malloc`. Sodium provides guard pages and uses mlock to avoid the secret memory area being swapped to disk.

We should create a new backend in rosenpass-secret-memory that:

- Uses [memfd_secret(2)](https://man.archlinux.org/man/memfd_secret.2.en) and guard pages using [mmap(2)](https://man.archlinux.org/man/mmap.2)
- If memfd_secret is unavailable, we should implement the same strategy as sodium guard pages and [mlock(2)](https://man.archlinux.org/man/mlock.2)
- Failing that we should continue to provide a sodium based secret memory backend
- Or allow users to specify that a dummy implementation using plain memory allocation should be used

**Comment by WcaleNieWolny** [comment]
The requirements for getting the pages is quite simple. Essentially you want to get a secured page in pure rust without sodium and if neither `mlock` or `memfd_secret` work you would like to 
A) use sodium 
B) use normal malloc (plain allocation)

That should not be to difficult, however I never implemented an allocator. How would you like to go from getting secure pages into malloc like fn? Is there any allocator library you would like to use that could use the secure pages?

**Comment by wucke13** [comment]
Hi, I like the discussion here. However, I feel that we might have overlooked an obvious and elegant solution: what speaks against using https://github.com/quininer/memsec ?

- It is pure Rust
- has about 500k downloads on crates.io, so is not super-niche
- slim on dependencies
- provides the functionality for Linux and Windows out of the box

Further on, I don't understand why we want to use `memfd` in particular? It seems that allocating a in-memory file to then get that file memory mapped is just extra steps compared to mlocking the memory directly and mprotecting before/behind the used memory?

Last but not least, I do not fancy auto-detection of this during runtime, that is unnecessary complexity. AFAIK any relevant platform either has mlock + mprotect (*Unix) or VirtualLock + VirtualProtect (Windows), so why bother with either Linux specifics and/or C libraries?

**Comment by koraa** [comment]
We decided to close the PR #179 since it was woefully incorrect, untested and insecure. For the next person to attempt this, please study the comments for a hint about what not to do.

I do not appreciate spending three hours to review a piece of code where the author obviously has not spent the same care to write it.

**Comment by ilka-schulz** [comment]
ftr: I think the PR which @koraa wanted to mention is #195.

**Comment by Sambit003** [comment]
@koraa Hi Karolin, Can we discuss about this issue in discord ?

**Comment by avdb13** [comment]
@Sambit003 it's been 6 weeks, mind letting someone else try?

**Comment by Sambit003** [comment]
> @Sambit003 it's been 6 weeks, mind letting someone else try?

@avdb13 I'm still working on this thing. As ensuring the safety of the things are crucial☺️.

**Comment by koraa** [comment]
@Sambit003 How about you start to share some of your progress and allow for some avenues for @avdb13 to collaborate?

Bounty size is not an issue here, but I don't think its useful for the project to block topics.

Anyway, thank you for your work on this :)

**Comment by Sambit003** [comment]
> @Sambit003 How about you start to share some of your progress and allow for some avenues for @avdb13 to collaborate?
> 
> Bounty size is not an issue here, but I don't think its useful for the project to block topics.
> 
> Anyway, thank you for your work on this :)

@koraa , I can go for a collab with @avdb13 ...right ? If yes then I will be sharing the progress soon

**Comment by koraa** [comment]
@Sambit003 Awesome! Thank you!

**Comment by prabhpreet** [comment]
Closing in lieu of #320
