### ISSUE TITLE
Config file does not support referring to home directory using `~`

### ISSUE THREAD

**Issue by blipp** [rosenpass/rosenpass#237]
In my test, the file `~/projects/rosenpass/testsetup01/rp-peer1-public-key` definitely existed. Rosenpass complains, claiming that it does not exist:

```
blipp@ernst:~/projects/rosenpass/target/debug$ ./rosenpass exchange-config ../../testsetup01/rp-peer1
[2024-02-01T14:07:11Z ERROR rosenpass] public-key file "~/projects/rosenpass/testsetup01/rp-peer1-public-key" does not exist
```

**Comment by ilka-schulz** [comment]
Is this actually a bug?

1. I think that `~` expansion is done by the shell and most programs do not do expansion on paths provided in their config files.
2. Also, the value of `~` depends on the user who runs the command.
3. I personally would not even be quite sure if I were always able to correctly identify the string to which `~` expands.

@blipp What do you think about that?

**Comment by ilka-schulz** [comment]
I had a talk with @koraa yesterday and we think that the following would be a good solution:
1. substitute `~\` and `~/` at the start of a path
2. do *not* substitute anything else
3. provide the tooling to create config files from shell (see #247)

I will start to implement that.
