### ISSUE TITLE
Secret not zeroized in key.rs line 94

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#287]
https://github.com/rosenpass/rosenpass/blob/0257aa9e15311d7d66982b646e711878b086f0f4/rp/src/key.rs#L94

Secret not zeroized

**Comment by emilengler** [comment]
Are you referring to the temporary `fs::read_from_file` call inside the function? Because the `Secret` struct should erase itself with the drop trait IIRC.

**Comment by koraa** [comment]
`fs::read_to_string(private_wgsk)?` produces one copy of the key.
`base64::engine::general_purpose::STANDARD.decode(fs::read_to_string(private_wgsk)?)` produces at least one, maybe multiple ones

**Comment by emilengler** [comment]
I will be working on this tomorrow
