### ISSUE TITLE
Secret memory with memfd_secret

### ISSUE THREAD

**Issue by prabhpreet** [rosenpass/rosenpass#320]
create a new backend in rosenpass-secret-memory that uses [memfd_secret(2)](https://man.archlinux.org/man/memfd_secret.2.en) and guard pages using [mmap(2)](https://man.archlinux.org/man/mmap.2)

**Comment by emilengler** [comment]
I am indifferent about the use of a Linux specific API. We might use some compiler options to enable it on Linux targets, but a similar functionality across all platforms is also desirable

**Comment by prabhpreet** [comment]
> I am indifferent about the use of a Linux specific API. We might use some compiler options to enable it on Linux targets, but a similar functionality across all platforms is also desirable

True. Let's start with the Linux specific APIs and approach other platforms incrementally.
