### ISSUE TITLE
CI is failing on main due to nix issues

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#47]
I don't think these problems have anything with the recently merged documentation change

```
Failed to load /nix/store/7habp8pc2jwvv17v6kx8wlidndxskqpb-dotnet-runtime-6.0.15/shared/Microsoft.NETCore.App/6.0.15/libcoreclr.so, error: /nix/store/5lp5v0sa76mhvc42bdc4z8vxwysp18r9-gcc-11.3.0-lib/lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /nix/store/vl893j5kphwcnqyf3qrxcmmjc8zrfa5q-icu4c-72.1/lib/libicuuc.so)
```

**Comment by wucke13** [comment]
I don't get why, but the github action runners fail eventually, and the only way of fixing them that I found so far is removing them (which is not actually registered in the WebUI, they just stay there even after clicking on "remove) and re-registering, which unfortunately requires new tokens to be generated, one per runner. I'm frustrated with this. However, the runners are up and runnin' now, lets see about the actual failure that was evident last time in the logs.

**Comment by wucke13** [comment]
Seems it works _for now_. I did not repair anything, but it does not break atm, so closing _for now_.
