### ISSUE TITLE
documentation: readability of getting started section

### ISSUE THREAD

**Issue by ilka-schulz** [rosenpass/rosenpass#49]
The [Getting Started](https://rosenpass.eu/#start) section on your website looks awesome but it could be easier to read for the typical ADHD programmer recipient:

1. The section starts with an explanation which is rather distracting from the "getting started" part than contributing to it. --> Maybe put it further down on the page for the more interested reader?
2. Each command is either executed on the "server" or the "client" and you mention this information in the text. --> Maybe put this information to the beginning of each command line like `user@server:~$ ` or `user@client:~$`, potentially even in different colors.
3. Some steps are documented as commands and some steps are documented in running text. --> Maybe use bullet points or any other method of itemization to visualize where one step ends and another one starts.

This is probably all not very urgent but I have witnessed time and time again how an "ADHD-friendly" README or "Getting Started" decides the game which tool gets used in the end and which one is ignored despite being a good tool.

**Comment by koraa** [comment]
@AliceOrunitia This is a quick win. Want do give it a try?

**Comment by AliceOrunitia** [comment]
Is this friendlier for a quick scan read?
![image](https://github.com/rosenpass/rosenpass/assets/121826205/b58e667c-3a9b-448f-abf5-a61d950037ee)

**Comment by koraa** [comment]
@ilka-schulz What do you think? Does this fulfill your needs?

**Comment by ilka-schulz** [comment]
That is much more readable already! :heart_eyes_cat: 

I still have a couples things to add:
1. the various indentations and enumerations could be indented for better readability
2. colorful `user@server` or `user@client` items would be great
3. you could start the first section with some caption, e.g. `Getting help`. The second section starts with the caption `Set Up Rosenpass` which is great but the first section could use a caption as well.
4. You could add some "copy-to-clipboard-button" or some view where the user can get the entire setup shell commands and copy them to their editor.
5. If it fits onto the web page, you could put the client commands into a left column and the server commands into a right column.

**Comment by AliceOrunitia** [comment]
All changes implemented :)
