### ISSUE TITLE
(homepage) Redirect from http:// to https://

### ISSUE THREAD

**Issue by chloe-the-catgirl** [rosenpass/rosenpass#50]
_(not sure, whether this is the correct place to report this, but since it's the only repository, I'll do it nonetheless.)_

A recent [toot from the official Rosenpass account](https://chaos.social/@rosenpass/110186253535787600) links to `http://rosenpass.eu`, likely by accident. And even though Firefox and other browsers do have a "use HTTPS by default" mode, not every browser has that as of today.

For example, I've opened the toot on my iPhone which opened the page using only HTTP. For a basic web page I wouldn't care. But Rosenpass is quite different and I think it would be beneficial to **redirect all HTTP requests to the HTTPS version**.

Furthermore, I'd recommend to **enable the `preload` directive** in the `Strict-Transport-Security` header, so that [Rosenpass can be submitted do the HSTS Preload list](https://hstspreload.org/?domain=rosenpass.eu).

(and thanks again for the nice talk at the #eh20, really enjoyed it! :relaxed:)

**Comment by koraa** [comment]
We should do that! Thank you for reporting!

**Comment by Mullana** [comment]
http redirects to https now!
