### ISSUE TITLE
Use internal man page

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#60]
While reviewing #53 , I noticed that the man invocation feature would fail to use the man command since I did not have the man page installed on my system. The feature would also show the system man page even if the system RP is different from the version I just compiled.

Both issues could be solved by including the man page source in the binary and doing the equivalent of:

    cat doc/rosenpass.1 | man /dev/stdin

**Comment by koraa** [comment]
@emilengler tagging you because you created the PR
@AliceOrunitia This is an easy one; you could take this if you are interested.

**Comment by emilengler** [comment]
It sounds like an interesting solution to me, although it would not perform very well on systems not having a `man(1)` installed, such as Alpine.

**Comment by koraa** [comment]
We could use the groff crate to render the generated man page on the fly. There even is a pager crate that we could integrate if there is no system pager

**Comment by wucke13** [comment]
Fixed by 8ff9b533 and b99d0728
