### ISSUE TITLE
Wrong PRF labels for chaining key extract/init

### ISSUE THREAD

**Issue by stv0g** [rosenpass/rosenpass#67]
- Page 8 mentions: `key chaining extract` & `key chaining init`
- Pages 9 & 18 mention: `chaining key extract` & `chaining key init`

Which constant should be used?

**Comment by koraa** [comment]
[labeled_prf.rs](https://github.com/rosenpass/rosenpass/blob/3856d774ff6c6954a3157d322d9846637d635c6a/src/labeled_prf.rs#L28)

**Comment by Mullana** [comment]
fixed!
