### ISSUE TITLE
IPv6 cloning support: Gitlab mirror

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#71]
We should provide an official gitlab mirror to support IPv6-only deployments.

See #64:

> Why GitHub? What about IPv6-only nodes? Rosenpass is FLOSS. Is there a specific reason why GitHub, which is proprietary, is used then? Some FLOSS projects host Git instances themselves or use free ones like codeberg.org. I had several times in the past on IPv6-only nodes the problem to install Rust packages since Rust fetched the packages from GitHub. Does this problem exist with Rosenpass as well? Building rosenpass locally on an IPv6-only node is also impossible, as the source code would have to be downloaded from GitHub. If not switching from GitHub, is the plan to do a mirror on an IPv6 Git instance?

**Comment by koraa** [comment]
@AliceOrunitia How would you feel about taking this?

**Comment by AliceOrunitia** [comment]
Absolutely! Just had a look. If we use its free web-hosted tier, we would be limited to 10GB of data transfers, with 5GB storage, per month. That includes end user downloads. Is that likely to be enough of an issue to want to host our own GitLab space, given that it's 30 bucks a month for 100GB of transfers. That's before we consider "compute units", although I don't think our current set up is that resource heavy in terms of the hosted runners. 

If all that seems fine, I can attempt to set up a mirror with a "rosenpass" account presently.

**Comment by AliceOrunitia** [comment]
https://gitlab.com/rosenpass/rosenpass

All up and mirrored. Unfortunately, setting it to automatically mirror is a premium function, so I have simply added personal notifications for changes to the github repo and will manually push changes as and when.

 I believe there are branch protection rules that currently prevent me from pushing any branches other than main, as they all complain of "(deny updating a hidden ref)". I'd either need sufficient permissions or for us to be happy with only main being there.

**Comment by koraa** [comment]
We could use a github action to sync the two :D

**Comment by koraa** [comment]
Oh and could you convert the Rosenpass account to an organization and add me (https://gitlab.com/dakora) to the org?

**Comment by AliceOrunitia** [comment]
Done :)

And github actions is a good shout. It would largely be a modification of what I have already written.

**Comment by marek22k** [comment]
Alternatively I can recommend notabug.org as a hosting platform. It is run by a kind of association and has specialized in free software. Furthermore you can use the mirror feature for free. (That's what I do for example. My main repo is at codeberg.org and as security I have set up a mirror on notabug.org).

**Comment by AliceOrunitia** [comment]
That's a fantastic alternative. Just set it up. Thank you.

Link:
https://notabug.org/rosenpass/rosenpass

**Comment by wucke13** [comment]
I set up a mirror, which is updated once a day: https://gitlab.com/rosenpass/rosenpass/ . I'm really not impressed at the amount of friction GitLab introduced in the simple task of running a `git push` from inside a GitLab CI.

I'm sure between this and the solution @AliceOrunitia provided something should work for you :smile: 

If not, please let us know here.

**Comment by koraa** [comment]
@wucke13 @marek22k @AliceOrunitia I think having both is great! We can offer a list of official mirrors for our software!

@wucke13 Thank you for doing the work of setting up the gitlab mirror.
@AliceOrunitia Could you create an issue for putting the list of mirrors on the website?
