### ISSUE TITLE
Backwards compatibility for `keygen` command

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#73]
Instead of just exiting, we should accept the parameter and ouput a deprecation warning.

**Comment by koraa** [comment]
@wucke13 What is the status of this?

**Comment by wucke13** [comment]
This is still missing. It basically boils down to looking at the history how the keygen used to look like, and then adding it to the big enum in `cli.rs`.

/bounty 15

**Comment by wucke13** [comment]
closed via #197

**Comment by ilka-schulz** [comment]
[Algora Documentation](https://docs.algora.io/commands) says that bounties need to be closed with `/approve`. Otherwise they stay open. E.g. this bounty is marked as still open.
