### ISSUE TITLE
Reliable dual stack setups

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#77]
My server has two public ips; I might use the following specification to listen on both public facing ips on port 5555: `listen '95.216.24.30:55555' listen '[2a01:4f9:2a:1861::2]:55555'`

If instead I wanted to listen on all IPs, I might use to specify the port:  `listen '0.0.0.0:55555' listen '[::]:55555'`.

The latter would raise an error on linux systems since `listen '[::]:55555'` will have rosenpass listen on both IPv4 and IPv6 addresses, port 55555 due to the dual-stack feature on those systems.

We should introduce a `listen-all 55555` option that will listen on any available address, port 55555. Additionally, we should automatically detect any-interface listen specifications for both ipv4 and ipv6 bind-all addresses and automatically handle dual-stack setups on all platforms (in this case rosenpass should behave as if `listen-all` was given.

**Comment by emilengler** [comment]
> The latter would raise an error on linux systems since listen '[::]:55555' will have rosenpass listen on both IPv4 and IPv6 addresses, port 55555 due to the dual-stack feature on those systems.

You can change that by setting a socket IPv6 only in Linux, before `bind(2)`ing it.

The C Programmer would do the following:
```c
int on = 1;
int sock = socket(...);

if (setsockopt(sock, IPPROTO_IPV6, IPV6_V6ONLY, &on, sizeof(on)) == -1)
    err(1, "setsockopt(2) failed");
```

**Comment by koraa** [comment]
@emilengler  Those apis are not available in rust

**Comment by emilengler** [comment]
> @emilengler  Those apis are not available in rust

The libc crate offers the setsockopt function. I know that this sounds a bit dirty, but can't we just get the raw FD from the socket and do a tiny libc invocation here?

**Comment by koraa** [comment]
> > @emilengler  Those apis are not available in rust
> 
> The libc crate offers the setsockopt function. I know that this sounds a bit dirty, but can't we just get the raw FD from the socket and do a tiny libc invocation here?

I mean if we where desperate we could do that, but its not very portable at all and we can read the value of the option…this allows us to reliably implement dual stack setups:

1. Open the ipv6 socket
2. Get the dual stack flag
3. Open the ipv4 socket, if ipv6 socket is not dual stack

It's more complicated than setting the flag, but its portable :)

**Comment by koraa** [comment]
Implemented!
