### ISSUE TITLE
Command line usage information is confusing for `rosenpass exchange` sub-command

### ISSUE THREAD

**Issue by stv0g** [rosenpass/rosenpass#87]
I am wondering why `[peer]` and the following `[public-key]` options are optional (e.g. `[]`)?

```
Usage: rosenpass exchange [OPTIONS] <OWN_CONFIG> [peer] [public-key] [<PATH>] [[ENDPOINT]] [[PSK]] [[OUTFILE]] [[WG]]...
```

Does this mean that the use of the `peer` and `public-key` keywords are in fact optional?

#### Example

```
rosenpass exchange public-key /my-public-key secret-key /my-secret-key /peer-a-public-key 1.2.3.4:1234
```

**Comment by wucke13** [comment]
Hi @stv0g , the particular semantics of this CLI are more detailed than I would know how to formulate them in a man page compatible grammar.
First of all, yes specifying no peers at all is intentionally allowed. Rosenpass is not terribly useful in that state, but oh well. This is still useful to test that basic functionality such as loading the key from disk actually works. And I don't see harm in running Rosenpass like that.

**If** a peer is specified, a public-key associated to that peer is mandatory. all other peer options can be omitted.

Anyhow, I tried to clarify the CLI a little, and I'd love to hear what do you think of it:

```
Usage: rosenpass exchange [OPTIONS] <OWN_CONFIG> [PEERS]...

Arguments:
  <OWN_CONFIG>
          public-key <PATH> secret-key <PATH> [listen <ADDR>:<PORT>]... [verbose]

  [PEERS]...
          peer public-key <PATH> [ENDPOINT] [PSK] [OUTFILE] [WG]
          
          ENDPOINT := endpoint <HOST/IP>:<PORT>
          
          PSK := preshared-key <PATH>
          
          OUTFILE := outfile <PATH>
          
          WG := wireguard <WIREGUARD_DEV> <WIREGUARD_PEER> [WIREGUARD_EXTRA_ARGS]...

Options:
  -c, --config-file <CONFIG_FILE>
          Save the parsed configuration to a file before starting the daemon

  -h, --help
          Print help (see a summary with '-h')
  ```
