### ISSUE TITLE
Use NIST PQC Round 4 implementation of Classic McEliece

### ISSUE THREAD

**Issue by stv0g** [rosenpass/rosenpass#91]
Blockers:

- [ ] OQS Version 9 ((Milestone)[https://github.com/open-quantum-safe/liboqs/milestone/22], (OQS 9 RC 1)[https://github.com/open-quantum-safe/liboqs/releases/tag/0.9.0-rc1])
- [ ] oqs-sys OQS 9 Support [Bump PR 1](https://github.com/open-quantum-safe/liboqs-rust/pull/241)

---

[Cloudflare's CIRCL McEliece implementation](https://github.com/cloudflare/circl/pull/378) implements the KEM based on the NIST PQC round 4 specification.

Round 4 has removed the plaintext confirmation (pc) from the ciphertext and as a result uses 32-byte shorted secret keys which are incompatible with the liboqs implementation which is based on the Round 3 specification (or Round 2 which rosenpass is actually using).

The website of Classic McEliece also mentioned this explicitly [in their implementations section](https://classic.mceliece.org/impl.html):

> The older "pc" variants have 32 extra bytes in ciphertexts.

The Rosenpass whitepaper does not specify which version of the KEM must be used.

The Rust implementation of Rosenpass uses the even older Round 2 implementation provided by liboqs.

I propose to switch to the updated Round 4 version.

### See also
- https://github.com/cloudflare/circl/pull/378#issuecomment-1583889820
- https://classic.mceliece.org/mceliece-pc-20221023.pdf
- https://classic.mceliece.org/impl.html

**Comment by stv0g** [comment]
@koraa Should we maybe create a v1 milestone in GitHub to track the issues which need to be resolved before v1?

If you agree, I would add this issue to this milestone.

**Comment by koraa** [comment]
There is a Rosenpass 1.0.0 Project. Can you see that?

**Comment by koraa** [comment]
https://crates.io/crates/pqcrypto

This might be a good alternative.

**Comment by clausecker** [comment]
Note that liboqs has switched to the round 4 specification with [oqs-sys v0.9.0](https://github.com/open-quantum-safe/liboqs-rust/blob/main/CHANGELOG.md).  Perhaps you could bump the dependency?

As a bonus, this would also permit unbundling liboqs as per issue #19.

**Comment by prabhpreet** [comment]
#266  or #292 will close this in the implementation

**Comment by prabhpreet** [comment]
Closed by #292
