### ISSUE TITLE
Rust log parameter on the CLI

### ISSUE THREAD

**Issue by koraa** [rosenpass/rosenpass#92]
--log-level info parameter should work
-v / -q should work

@wucke13

**Comment by b4s36t4** [comment]
@koraa right now we have Verbose taking from config file, adding `-q` and `-v` doesn't cause an issue?

I'm thinking to turn off the logging i.e using `env_logger` when `config.verbosity` is `Verbosity::Quiet`, how does that sound?

**Comment by koraa** [comment]
@wucke13 @emilengler What do you think?

**Comment by wucke13** [comment]
I would like to differentiate between silent (which really means no logging at all) and quiet (which means only error and warning, which normally does not happen). Does that make sense?

**Comment by ezhil56x** [comment]
@koraa Can you explain a bit more about this. I would like to give a try if I can

**Comment by koraa** [comment]
> @koraa Can you explain a bit more about this. I would like to give a try if I can

Well it would be good if it was possible to set the log level on the command line as a convenience feature.

- `--log-level LEVEL`
- `-v/--verbose` (sets log level info)
- `-q/--quiet` (sets log level error)

**Comment by ezhil56x** [comment]
@koraa

I hope this needs to added in the required `rp`. Correct me if I'm wrong

**Comment by b77686f616d69** [comment]
Can I try to work on this

**Comment by Rutik7066** [comment]
hey is this issue still need some work?

**Comment by koraa** [comment]
@Rutik7066 I have seen no PR from @Sambit003

**Comment by emilengler** [comment]
> @wucke13 @emilengler What do you think?

I believe it is okay if we just use trace/debug/info/warning/error. Those are well-established identifier introduced by log4j in the mid-90s. Chance for ambiguity is pretty low.

**Comment by ilka-schulz** [comment]
implemented in PR #246
